import React, { useState, useEffect, useRef } from 'react';
import { X, Upload, Sparkles, TrendingUp, Image as ImageIcon, CheckCircle, AlertCircle, Loader2, Settings, ThumbsUp, ThumbsDown, AlertTriangle, Info, ChevronUp, ChevronDown } from 'lucide-react';
import { geminiService, GeminiClothingAnalysis } from '../services/geminiVisionService';
import { imageComparisonService, ComparisonResult, EnhancedSimilarityResult } from '../services/imageComparisonService';
import { collageService } from '../services/collageService';
import { salesHistoryService, ProductSalesData } from '../services/salesHistoryService';
import { hasGeminiAPIKey, loadGeminiAPIKey, loadGLMAPIKey, hasAPIKeyWithFallback, loadAPIKeyWithFallback } from '../utils/encryption';
import GeminiAPISettings from './GeminiAPISettings';
import { Product } from '../types';

interface AIAutoUploadModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: (productData: any) => void;
  existingProducts: Product[]; // For similarity comparison
}

type Step = 'upload' | 'analyzing' | 'results' | 'collage';

interface AnalysisResult {
  imageIndex: number;
  fileName: string;
  analysis: GeminiClothingAnalysis;
  imageBase64: string; // Store base64 for direct comparison
  processingTime: number;
}

interface SimilarityResult {
  product: Product;
  score: ComparisonResult;
  salesLast3Months: number;
  aiReasoning?: string;
}

interface EnhancedSimilarityResultUI extends EnhancedSimilarityResult {
  product: Product;
  sourceImageIndex?: number;
  modelComparison?: string;
  motifComparison?: string;
}

// Interface for pricing rules - used in auto upload settings
interface PricingRule {
  id: string;
  minCost: number;
  maxCost: number;
  retailMarkup: number;
}

// Helper function to calculate profit (Markup)
const calculateProfit = (retail: number, cost: number) => {
  if (!retail || !cost) return 0;
  return Math.round(((retail - cost) / cost) * 100);
};

export const AIAutoUploadModal: React.FC<AIAutoUploadModalProps> = ({
  isOpen,
  onClose,
  onSuccess,
  existingProducts
}) => {
  // Step management
  const [step, setStep] = useState<Step>('upload');

  // Upload step
  const [images, setImages] = useState<File[]>([]);
  const [imagePreviews, setImagePreviews] = useState<string[]>([]);
  const [dragOver, setDragOver] = useState(false);

  // Analysis step
  const [analysisResults, setAnalysisResults] = useState<AnalysisResult[]>([]);
  const [analyzingIndex, setAnalyzingIndex] = useState(0);
  const [analysisProgress, setAnalysisProgress] = useState(0);
  const [analysisError, setAnalysisError] = useState<string | null>(null);

  // Results step
  const [similarityResults, setSimilarityResults] = useState<SimilarityResult[]>([]);
  const [enhancedSimilarityResults, setEnhancedSimilarityResults] = useState<EnhancedSimilarityResultUI[]>([]);
  const [recommendation, setRecommendation] = useState<'auto' | 'manual' | 'not_recommended'>('manual');
  const [comparativeAnalysis, setComparativeAnalysis] = useState<{
    topSimilarities: Array<{
      productName: string;
      similarityScore: number;
      keySimilarities: string[];
      recommendation: string;
      reasoning: string;
    }>;
    overallRecommendation: string;
    marketInsights: string[];
  } | null>(null);

  // Collage step
  const [collageBlob, setCollageBlob] = useState<Blob | null>(null);
  const [collagePreview, setCollagePreview] = useState<string | null>(null);
  const [variantLabels, setVariantLabels] = useState<string[]>([]);
  const [uploadMode, setUploadMode] = useState<'direct' | 'review'>('review'); // New: Direct upload vs Review first
  const [productFormData, setProductFormData] = useState({
    name: '',
    retailPrice: '',
    resellerPrice: '',
    category: 'Gamis',
    stockPerVariant: {} as Record<string, string>, // Changed: Individual stock per variant
    costPrice: '', // New: Modal produk untuk hitung laba
    description: '', // New: Auto-generated by AI but can be edited
    profitMargin: 0 // New: Calculated profit
  });

  // Auto Upload Settings (Global)

  // State for Settings with Persistence
  const [autoUploadSettings, setAutoUploadSettings] = useState<{
    stock: number;
    costPrice: number;
    resellerDiscount: number;
    enableCustomLogic: boolean;
    pricingRules: PricingRule[];
  }>(() => {
    // Try to load from localStorage on init
    const saved = localStorage.getItem('autoUploadSettings');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch (e) {
        console.error('Failed to parse saved settings', e);
      }
    }
    // Default values if no saved settings
    return {
      stock: 5,
      costPrice: 100000,
      resellerDiscount: 20000,
      enableCustomLogic: true,
      pricingRules: [
        { id: '1', minCost: 0, maxCost: 100000, retailMarkup: 20000 },
        { id: '2', minCost: 100001, maxCost: 200000, retailMarkup: 30000 },
        { id: '3', minCost: 200001, maxCost: 500000, retailMarkup: 50000 },
      ]
    };
  });

  // Save settings on change
  useEffect(() => {
    localStorage.setItem('autoUploadSettings', JSON.stringify(autoUploadSettings));
  }, [autoUploadSettings]);

  const [showSettings, setShowSettings] = useState(false);
  const submittingRef = useRef(false);
  const [hasAPIKey, setHasAPIKey] = useState(false);
  const [showAPISettings, setShowAPISettings] = useState(false);

  useEffect(() => {
    if (isOpen) {
      const checkAPIKey = async () => {
        // Check API key with global storage fallback
        const apiKeyExists = await hasAPIKeyWithFallback('gemini') || await hasAPIKeyWithFallback('glm');
        setHasAPIKey(apiKeyExists);

        if (apiKeyExists) {
          try {
            // Load keys with global storage fallback
            const apiKey = await loadAPIKeyWithFallback('gemini');
            const glmApiKey = await loadAPIKeyWithFallback('glm');

            if (apiKey || glmApiKey) {
              geminiService.initialize(apiKey || '', glmApiKey || '');
            }
          } catch (error) {
            console.error('Failed to initialize AI service:', error);
          }
        } else {
          setShowAPISettings(true);
        }
      };

      checkAPIKey();
    }
  }, [isOpen]);

  // Reset state when modal closes
  useEffect(() => {
    if (!isOpen) {
      setStep('upload');
      setImages([]);
      setImagePreviews([]);
      setAnalysisResults([]);
      setSimilarityResults([]);
      setCollageBlob(null);
      setCollagePreview(null);
      setAnalysisError(null);
      setRecommendation('manual');
      setUploadMode('review');
      setProductFormData({
        name: '',
        retailPrice: '',
        resellerPrice: '',
        category: 'Gamis',
        stockPerVariant: {} as Record<string, string>,
        costPrice: '',
        description: '',
        profitMargin: 0
      });
    }
  }, [isOpen]);

  // Handle image upload
  const handleFileSelect = (files: FileList | null) => {
    if (!files) return;

    const selectedFiles = Array.from(files).slice(0, 9); // Max 9 images
    const validFiles: File[] = [];
    const previews: string[] = [];

    selectedFiles.forEach(file => {
      if (file.type.startsWith('image/')) {
        validFiles.push(file);
        previews.push(URL.createObjectURL(file));
      }
    });

    // Add to existing images (max 9 total)
    const totalImages = [...images, ...validFiles].slice(0, 9);
    const totalPreviews = [...imagePreviews, ...previews].slice(0, 9);

    setImages(totalImages);
    setImagePreviews(totalPreviews);

    // Generate variant labels
    const labels = collageService.generateVariantLabels(totalImages.length);
    setVariantLabels(labels);

    // Initialize stock per variant
    const initialStock: Record<string, string> = {};
    labels.forEach(label => {
      initialStock[label] = '10'; // Default 10 stock per variant
    });
    setProductFormData(prev => ({
      ...prev,
      stockPerVariant: initialStock
    }));
  };

  const removeImage = (index: number) => {
    const newImages = images.filter((_, i) => i !== index);
    const newPreviews = imagePreviews.filter((_, i) => i !== index);

    // Revoke object URL
    URL.revokeObjectURL(imagePreviews[index]);

    setImages(newImages);
    setImagePreviews(newPreviews);

    // Update labels and stock
    const labels = collageService.generateVariantLabels(newImages.length);
    setVariantLabels(labels);

    // Update stock per variant
    const newStock: Record<string, string> = {};
    labels.forEach(label => {
      newStock[label] = productFormData.stockPerVariant[label] || '10'; // Keep existing stock or default to 10
    });
    setProductFormData(prev => ({
      ...prev,
      stockPerVariant: newStock
    }));
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    handleFileSelect(e.dataTransfer.files);
  };

  // Start analysis
  const startAnalysis = async () => {
    if (images.length < 1) {
      alert('Please upload at least 1 image');
      return;
    }

    if (!geminiService.isInitialized()) {
      alert('Gemini API not initialized. Please configure API key first.');
      return;
    }

    setStep('analyzing');
    setAnalysisError(null);
    setAnalysisProgress(0);

    try {
      // OPTIMIZATION: Only analyze the FIRST image for faster processing
      console.log('🚀 AI Analysis: Analyzing only first image for faster processing');
      const firstImageBase64 = await collageService.fileToBase64(images[0]);

      const results: AnalysisResult[] = [];

      // Analyze only the first image
      setAnalyzingIndex(0);
      const startTime = Date.now();

      try {
        const analysis = await geminiService.analyzeClothingImage(firstImageBase64);
        const endTime = Date.now();

        results.push({
          imageIndex: 0,
          fileName: images[0].name,
          analysis,
          imageBase64: firstImageBase64, // Store base64 for direct comparison
          processingTime: endTime - startTime
        });

        // Fast progress since we're only analyzing one image
        setAnalysisProgress(50); // 50% for analysis
      } catch (error: any) {
        console.error(`Analysis failed for first image:`, error);
        throw new Error(`Failed to analyze image: ${error.message}`);
      }

      setAnalysisResults(results);

      // Generate auto-description based on analysis
      if (results[0]?.analysis) {
        const analysis = results[0].analysis;
        const autoDescription = `${images.length} varian: ${variantLabels.join(', ')}. Model ${analysis.clothing_type.main_type} dengan motif ${analysis.pattern_type.pattern}${analysis.lace_details.has_lace ? ' dan detail lace' : ''}${analysis.hem_pleats.has_pleats ? ' serta detail lipatan bawah' : ''}.`;

        setProductFormData(prev => ({
          ...prev,
          description: autoDescription
        }));
      }

      // Calculate similarity with existing products
      await calculateSimilarity(results);

      setAnalysisProgress(100);
      setStep('results');

    } catch (error: any) {
      console.error('Analysis error:', error);
      setAnalysisError(error.message || 'Analysis failed. Please try again.');
    }
  };

  // Calculate similarity with existing products using Enhanced Algorithm
  const calculateSimilarity = async (analysisResults: AnalysisResult[]) => {
    setAnalysisProgress(60);

    if (existingProducts.length === 0) {
      setRecommendation('manual');
      setSimilarityResults([]);
      setEnhancedSimilarityResults([]);
      return;
    }

    try {
      console.log('📊 Step 1: Filtering products by sales...');

      // STEP 1: Get products with sales > 4pcs (3 months) using new method
      const productsWithGoodSalesData = await salesHistoryService.getProductsWithMinSales(4, 3);

      console.log(`✓ Found ${productsWithGoodSalesData.length} products with >4pcs sales (last 3 months)`);

      if (productsWithGoodSalesData.length === 0) {
        console.log('⚠️ No products with sufficient sales history');
        setRecommendation('not_recommended');
        setSimilarityResults([]);
        setEnhancedSimilarityResults([]);
        setAnalysisProgress(100);
        return;
      }

      // Map sales data to existing products
      const productsWithGoodSales = existingProducts.filter(p =>
        productsWithGoodSalesData.some(sales => sales.productId === p.id)
      );

      // Get AI analysis for existing products (or use cached)
      const existingProductsWithAnalysis = await Promise.all(
        productsWithGoodSales.map(async (product) => {
          try {
            // Try to get existing analysis from product data
            if (product.aiAnalysis) {
              console.log('📁 Using cached AI analysis for:', product.name, product.aiAnalysis);

              // Normalize cached analysis to ensure consistent format
              const cachedAnalysis = product.aiAnalysis as any;
              const normalizedAnalysis: GeminiClothingAnalysis = {
                clothing_type: {
                  main_type: (cachedAnalysis.clothing_type?.main_type || 'other').toLowerCase(),
                  silhouette: (cachedAnalysis.clothing_type?.silhouette || 'loose').toLowerCase(),
                  length: (cachedAnalysis.clothing_type?.length || 'maxi').toLowerCase(),
                  confidence: cachedAnalysis.clothing_type?.confidence || 50
                },
                pattern_type: {
                  pattern: (cachedAnalysis.pattern_type?.pattern || 'solid').toLowerCase(),
                  complexity: (cachedAnalysis.pattern_type?.complexity || 'simple').toLowerCase(),
                  confidence: cachedAnalysis.pattern_type?.confidence || 50
                },
                lace_details: {
                  has_lace: cachedAnalysis.lace_details?.has_lace || false,
                  locations: (cachedAnalysis.lace_details?.locations || []).map((loc: any) => ({
                    position: (loc.position || 'collar').toLowerCase(),
                    coverage: (loc.coverage || 'minimal').toLowerCase(),
                    lace_type: (loc.lace_type || 'floral_lace').toLowerCase()
                  })),
                  confidence: cachedAnalysis.lace_details?.confidence || 50
                },
                hem_pleats: {
                  has_pleats: cachedAnalysis.hem_pleats?.has_pleats || false,
                  pleat_type: (cachedAnalysis.hem_pleats?.pleat_type || 'none').toLowerCase(),
                  depth: (cachedAnalysis.hem_pleats?.depth || 'shallow').toLowerCase(),
                  fullness: cachedAnalysis.hem_pleats?.fullness || 0,
                  confidence: cachedAnalysis.hem_pleats?.confidence || 50
                },
                sleeve_details: {
                  has_pleats: cachedAnalysis.sleeve_details?.has_pleats || false,
                  sleeve_type: (cachedAnalysis.sleeve_details?.sleeve_type || 'straight').toLowerCase(),
                  pleat_position: (cachedAnalysis.sleeve_details?.pleat_position || 'wrist').toLowerCase(),
                  ruffle_count: cachedAnalysis.sleeve_details?.ruffle_count || 0,
                  cuff_style: (cachedAnalysis.sleeve_details?.cuff_style || 'plain').toLowerCase(),
                  confidence: cachedAnalysis.sleeve_details?.confidence || 50
                },
                embellishments: {
                  beads: cachedAnalysis.embellishments?.beads || { has: false, locations: [], density: 0 },
                  embroidery: cachedAnalysis.embellishments?.embroidery || { has: false, pattern: '' },
                  sequins: cachedAnalysis.embellishments?.sequins || { has: false, locations: [] },
                  gold_thread: cachedAnalysis.embellishments?.gold_thread || { has: false, coverage: 0 }
                },
                colors: (cachedAnalysis.colors || ['unknown']).map((c: string) => c.toLowerCase()),
                fabric_texture: (cachedAnalysis.fabric_texture || 'smooth').toLowerCase()
              };

              console.log('🔄 Normalized cached analysis:', normalizedAnalysis);

              return {
                product,
                analysis: normalizedAnalysis,
                salesData: productsWithGoodSalesData.find(s => s.productId === product.id)!
              };
            }

            // If no analysis, analyze main image
            const mainImageUrl = product.images[0] || product.image;
            if (!mainImageUrl) {
              throw new Error(`No image for product ${product.name}`);
            }

            // Fetch and analyze image
            const response = await fetch(mainImageUrl);
            const blob = await response.blob();
            const base64 = await collageService.fileToBase64(new File([blob], 'product.jpg'));

            const analysis = await geminiService.analyzeClothingImage(base64);

            return {
              product,
              analysis,
              imageBase64: base64, // Store base64 for direct comparison
              salesData: productsWithGoodSalesData.find(s => s.productId === product.id)!
            };
          } catch (error) {
            console.error(`Failed to analyze product ${product.name}:`, error);
            return null;
          }
        })
      );

      // Filter out failed analyses
      const validProductsWithAnalysis = existingProductsWithAnalysis.filter(
        (item): item is NonNullable<typeof item> => item !== null
      );

      console.log(`✓ Analyzed ${validProductsWithAnalysis.length} existing products`);

      if (validProductsWithAnalysis.length === 0) {
        console.log('⚠️ No valid product analyses available');
        setRecommendation('not_recommended');
        setSimilarityResults([]);
        setEnhancedSimilarityResults([]);
        setAnalysisProgress(100);
        return;
      }

      setAnalysisProgress(70);

      // STEP 2: Calculate enhanced similarity for each product
      console.log('🔍 Step 2: Calculating enhanced similarity scores...');

      if (analysisResults.length === 0) {
        throw new Error('No analysis results available for uploaded images');
      }

      const enhancedSimilarities: EnhancedSimilarityResultUI[] = [];

      // Use only the first uploaded image for similarity calculation
      const uploadedAnalysis = analysisResults[0]?.analysis;
      if (!uploadedAnalysis) {
        throw new Error('No analysis available for the first image');
      }

      console.log('📊 First image analysis:', {
        type: uploadedAnalysis?.clothing_type?.main_type,
        pattern: uploadedAnalysis?.pattern_type?.pattern,
        colors: uploadedAnalysis?.colors,
        hasLace: uploadedAnalysis?.lace_details?.has_lace
      });

      for (const item of validProductsWithAnalysis) {
        console.log('🔍 Comparing with product:', item.product.name);

        console.log('📊 Existing analysis:', {
          type: item.analysis?.clothing_type?.main_type,
          pattern: item.analysis?.pattern_type?.pattern,
          colors: item.analysis?.colors,
          hasLace: item.analysis?.lace_details?.has_lace
        });

        let similarityScore = 0;
        let aiReasoning = '';
        let modelComparison = '';
        let motifComparison = '';
        // Default breakdown for direct comparison
        let breakdown = {
          modelType: 0,
          pattern: 0,
          colors: 100,      // Colors ignored (weight: 0%)
          details: 100,     // Details ignored (weight: 0%)
          embellishments: 100 // Embellishments ignored (weight: 0%)
        };

        // Try direct comparison first (Gemini's recommended approach)
        try {
          const uploadedImageBase64 = analysisResults[0]?.imageBase64;
          let existingImageBase64 = item.imageBase64;

          // If no stored base64 for existing product, fetch it
          if (!existingImageBase64) {
            const mainImageUrl = item.product.images[0] || item.product.image;
            if (mainImageUrl) {
              const response = await fetch(mainImageUrl);
              const blob = await response.blob();
              existingImageBase64 = await collageService.fileToBase64(new File([blob], 'product.jpg'));
            }
          }

          if (uploadedImageBase64 && existingImageBase64) {
            console.log('🔍 Performing direct image comparison with Gemini API...');
            const directResult = await geminiService.directCompareImages(
              uploadedImageBase64,
              existingImageBase64
            );

            similarityScore = directResult.similarityScore;
            aiReasoning = directResult.explanation;
            modelComparison = directResult.modelComparison;
            motifComparison = directResult.motifComparison;

            // Update breakdown for direct comparison
            breakdown = {
              modelType: similarityScore, // Model similarity score
              pattern: similarityScore,   // Pattern similarity score  
              colors: 100,               // Colors ignored (weight: 0%)
              details: 100,              // Details ignored (weight: 0%)
              embellishments: 100        // Embellishments ignored (weight: 0%)
            };

            console.log(`🎯 Direct comparison for ${item.product.name}: ${similarityScore}%`);
          } else {
            throw new Error('Missing base64 images for comparison');
          }
        } catch (error) {
          console.warn(`Direct comparison failed for ${item.product.name}:`, error);
          console.log('🔄 Falling back to enhanced similarity algorithm...');

          // Fallback to enhanced similarity
          const enhancedResult = imageComparisonService.calculateEnhancedSimilarity(
            uploadedAnalysis,
            item.analysis,
            {
              totalQuantity: item.salesData.totalQuantity,
              productName: item.product.name
            }
          );

          similarityScore = enhancedResult.overallScore;
          aiReasoning = enhancedResult.aiReasoning || '';
          // Use breakdown from enhancedResult for fallback
          breakdown = enhancedResult.breakdown || breakdown;
        }



        // Determine recommendation details
        const recommendationLevel = similarityScore >= 80 ? 'highly_recommended' :
          similarityScore >= 70 ? 'recommended' :
            similarityScore >= 50 ? 'consider' : 'not_recommended';

        const recommendationLabels = {
          highly_recommended: 'Highly Recommended - Strong market fit',
          recommended: 'Recommended - Good potential',
          consider: 'Consider - Niche market opportunity',
          not_recommended: 'Not Recommended - Low similarity'
        };

        const recommendationReasons = {
          highly_recommended: `Very high similarity (${similarityScore}%) with best-selling product`,
          recommended: `Good similarity (${similarityScore}%) with existing products`,
          consider: `Moderate similarity (${similarityScore}%) - niche opportunity`,
          not_recommended: `Low similarity (${similarityScore}%) with existing products`
        };

        enhancedSimilarities.push({
          productId: item.product.id,
          productName: item.product.name,
          overallScore: similarityScore,
          breakdown,
          salesLast3Months: item.salesData.totalQuantity,
          aiReasoning: aiReasoning,
          recommendation: recommendationLevel,
          recommendationLabel: recommendationLabels[recommendationLevel],
          recommendationReason: recommendationReasons[recommendationLevel],
          product: item.product,
          modelComparison,
          motifComparison
        });

        console.log(`🎯 Similarity for ${item.product.name}: ${similarityScore}% (${aiReasoning.substring(0, 50)}...)`);
      }

      // Sort by overall score (descending)
      enhancedSimilarities.sort((a, b) => b.overallScore - a.overallScore);

      setEnhancedSimilarityResults(enhancedSimilarities);
      setAnalysisProgress(80);

      // STEP 3: Generate comparative analysis with Gemini
      console.log('🤖 Step 3: Generating comparative analysis...');

      try {
        // Use first image analysis for comparative analysis
        const comparativeAnalysisUploaded = analysisResults[0]?.analysis;
        if (!comparativeAnalysisUploaded) {
          throw new Error('No analysis available for comparative analysis');
        }

        const comparativeAnalysis = await geminiService.generateComparativeAnalysis(
          comparativeAnalysisUploaded,
          validProductsWithAnalysis.map(item => ({
            product: item.product,
            analysis: item.analysis,
            salesData: {
              totalQuantity: item.salesData.totalQuantity,
              productName: item.product.name
            }
          })),
          3 // Top 3 products
        );

        setComparativeAnalysis(comparativeAnalysis);
        console.log('✓ Comparative analysis generated');
      } catch (error) {
        console.warn('Failed to generate comparative analysis:', error);
        // Continue without comparative analysis
      }

      setAnalysisProgress(90);

      // STEP 4: Determine overall recommendation
      console.log('📈 Step 4: Determining overall recommendation...');

      if (enhancedSimilarities.length === 0) {
        setRecommendation('not_recommended');
      } else {
        const topScore = enhancedSimilarities[0]?.overallScore || 0;

        if (topScore >= 80) {
          setRecommendation('auto'); // Highly recommended
        } else if (topScore >= 70) {
          setRecommendation('manual'); // Consider
        } else {
          setRecommendation('not_recommended');
        }
      }

      // Keep old similarity results for backward compatibility
      const oldSimilarities: SimilarityResult[] = enhancedSimilarities.map(item => ({
        product: item.product,
        score: {
          overall_similarity: item.overallScore,
          breakdown: {
            model_type: item.breakdown.modelType,
            motif_pattern: item.breakdown.pattern,
            lace_details: 0,
            hem_pleats: 0,
            sleeve_details: 0
          },
          visual_analysis: {
            image1_description: '',
            image2_description: '',
            key_similarities: [],
            key_differences: []
          },
          recommendation: item.recommendationLabel,
          confidence: 0,
          hash_similarity: 0
        },
        salesLast3Months: item.salesLast3Months,
        aiReasoning: item.aiReasoning
      }));

      setSimilarityResults(oldSimilarities);
      setAnalysisProgress(100);

      console.log('✅ Enhanced similarity analysis complete');
      console.log(`📊 Top similarity: ${enhancedSimilarities[0]?.overallScore || 0}%`);
      console.log(`🏷️ Recommendation: ${recommendation}`);

    } catch (error: any) {
      console.error('Error calculating similarity:', error);
      setRecommendation('manual');
      setSimilarityResults([]);
      setEnhancedSimilarityResults([]);
    }
  };

  // Generate collage
  const generateCollagePreview = async () => {
    try {
      const blob = await collageService.generateCollage(images, variantLabels);
      setCollageBlob(blob);

      const previewUrl = URL.createObjectURL(blob);
      setCollagePreview(previewUrl);

      setStep('collage');
    } catch (error: any) {
      console.error('Collage generation error:', error);
      alert('Failed to generate collage. Please try again.');
    }
  };

  // Calculate profit margin
  // Calculate profit margin
  // calculateProfit is now defined outside as a helper


  // Auto-calculate profit when prices change
  useEffect(() => {
    const retail = parseInt(productFormData.retailPrice) || 0;
    const cost = parseInt(productFormData.costPrice) || 0;
    const profit = calculateProfit(retail, cost);

    if (productFormData.profitMargin !== profit) {
      setProductFormData(prev => ({
        ...prev,
        profitMargin: profit
      }));
    }
  }, [productFormData.retailPrice, productFormData.costPrice]);

  // Submit product
  const handleSubmit = (overrideData?: any) => {
    // Prevent duplicate submission
    if (submittingRef.current) return;
    submittingRef.current = true;

    // Use override data if provided (for direct upload), otherwise use state
    const data = overrideData || productFormData;

    if (!data.name || !data.retailPrice || !data.resellerPrice) {
      alert('Please fill in all required fields');
      submittingRef.current = false; // Reset on error
      return;
    }

    if (!collageBlob) {
      alert('Collage not generated');
      submittingRef.current = false; // Reset on error
      return;
    }

    // Calculate total stock
    const totalStock = Object.values(data.stockPerVariant).reduce((sum: number, stock: any) => sum + parseInt(stock || '0'), 0);

    if (totalStock === 0) {
      alert('Please set stock for at least one variant');
      submittingRef.current = false; // Reset on error
      return;
    }

    // Create product data with collage
    const productData = {
      ...data,
      collageBlob,
      collageFile: new File([collageBlob], `collage-${Date.now()}.jpg`, { type: 'image/jpeg' }),
      variantLabels,
      analysisResults,
      similarityResults,
      variantCount: images.length,
      totalStock,
      uploadMode // Pass the selected upload mode
    };

    onSuccess(productData);
    // Note: submittingRef remains true to prevent double clicks until modal closes/resets
    setTimeout(() => { submittingRef.current = false; }, 3000); // Safety reset
  };

  // Handle direct upload
  const handleDirectUpload = () => {
    // Auto-generate AI caption if not provided
    const aiCaption = productFormData.description || `${images.length} varian premium dengan motif unik`;

    // Prepare final data synchronously to avoid state race conditions
    const finalData = {
      ...productFormData,
      description: productFormData.description || aiCaption,
      name: productFormData.name || `Gamis Premium ${variantLabels.join('-')}`,
      retailPrice: productFormData.retailPrice || '150000',
      resellerPrice: productFormData.resellerPrice || '135000',
      costPrice: productFormData.costPrice || '100000'
    };

    // Update form state (for UI consistency in case of error)
    setProductFormData(finalData);

    // Submit immediately with the data
    handleSubmit(finalData);
  };

  if (!isOpen) return null;

  // API Settings Screen
  if (showAPISettings) {
    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
          <div className="p-6 border-b border-gray-200 flex items-center justify-between sticky top-0 bg-white">
            <h2 className="text-xl font-bold text-gray-900">Configure Gemini API</h2>
            <button
              onClick={onClose}
              className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          <div className="p-6">
            <GeminiAPISettings
              onSave={() => {
                setHasAPIKey(true);
                setShowAPISettings(false);
              }}
              onClose={() => setShowAPISettings(false)}
            />
          </div>
        </div>
      </div>
    );
  }

  // Auto fill form data from existing product
  const handleAutoFillData = async (product: Product, analysis: GeminiClothingAnalysis) => {
    // Generate AI Marketing content
    const marketingContent = await geminiService.generateMarketingContent(analysis, product.name);

    // Apply Logic from Settings
    const { stock, costPrice, resellerDiscount, enableCustomLogic, pricingRules } = autoUploadSettings;

    // 1. Cost Price (costPrice dari settings atau dari product)
    const finalCost = enableCustomLogic ? costPrice : (product.costPrice || product.retailPrice * 0.6);

    // 2. Retail Price - Find matching pricing rule based on cost
    let finalRetail = product.retailPrice;
    if (enableCustomLogic && pricingRules.length > 0) {
      // Find the pricing rule that matches the cost price range
      const matchingRule = pricingRules.find(
        rule => finalCost >= rule.minCost && finalCost <= rule.maxCost
      );

      if (matchingRule) {
        finalRetail = finalCost + matchingRule.retailMarkup;
        console.log(`✓ Applied pricing rule: Modal ${finalCost} dalam range ${matchingRule.minCost}-${matchingRule.maxCost}, markup +${matchingRule.retailMarkup}`);
      } else {
        // If no matching rule, use the highest rule's markup as fallback
        const highestRule = pricingRules.reduce((prev, current) =>
          (prev.maxCost > current.maxCost) ? prev : current
        );
        finalRetail = finalCost + highestRule.retailMarkup;
        console.log(`⚠️ No matching pricing rule for cost ${finalCost}, using default markup +${highestRule.retailMarkup}`);
      }
    }

    // 3. Reseller Price = Retail - Discount
    let finalReseller = product.resellerPrice || finalRetail * 0.9;
    if (enableCustomLogic && resellerDiscount > 0) {
      finalReseller = finalRetail - resellerDiscount;
    }

    // 4. Stock Allocation
    // Generate variant labels if empty (fallback)
    const currentLabels = variantLabels.length > 0 ? variantLabels : collageService.generateVariantLabels(images.length);
    const stockMap: Record<string, string> = {};
    if (enableCustomLogic) {
      currentLabels.forEach(l => stockMap[l] = stock.toString());
    } else {
      // Fallback to match similar product stock pattern or just 10
      currentLabels.forEach(l => stockMap[l] = '10');
    }

    setProductFormData(prev => ({
      ...prev,
      name: marketingContent.title, // AI Generated Title
      retailPrice: finalRetail.toString(),
      resellerPrice: finalReseller.toString(),
      costPrice: finalCost.toString(),
      category: analysis.clothing_type.main_type || product.category || 'Gamis',
      description: marketingContent.description, // AI Generated Caption
      stockPerVariant: stockMap
    }));
  };

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="p-6 border-b border-gray-200 flex items-center justify-between sticky top-0 bg-white z-10">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-gradient-to-r from-purple-600 to-blue-600 rounded-lg">
              <Sparkles className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-gray-900">🤖 AI Auto Upload</h2>
              <p className="text-sm text-gray-500">
                Upload 3-9 variant images for AI analysis
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowAPISettings(true)}
              className="p-2 hover:bg-gray-100 rounded-lg transition-colors text-gray-500"
              title="Configure Gemini API Key"
            >
              <Settings className="w-5 h-5" />
            </button>
            <button
              onClick={onClose}
              className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Progress Steps */}
        <div className="px-6 py-4 border-b border-gray-200 bg-gray-50">
          <div className="flex items-center justify-between max-w-2xl mx-auto">
            {[
              { id: 'upload', label: 'Upload', icon: Upload },
              { id: 'analyzing', label: 'Analyzing', icon: Sparkles },
              { id: 'results', label: 'Results', icon: TrendingUp },
              { id: 'collage', label: 'Collage', icon: ImageIcon }
            ].map((s, index) => {
              const isActive = step === s.id;
              const isCompleted = ['upload', 'analyzing', 'results', 'collage'].indexOf(step) > index;
              const Icon = s.icon;

              return (
                <React.Fragment key={s.id}>
                  <div className="flex flex-col items-center">
                    <div
                      className={`
                        w-10 h-10 rounded-full flex items-center justify-center mb-1 transition-all
                        ${isActive ? 'bg-purple-600 text-white shadow-lg' : ''}
                        ${isCompleted ? 'bg-green-600 text-white' : ''}
                        ${!isActive && !isCompleted ? 'bg-gray-200 text-gray-400' : ''}
                      `}
                    >
                      {isCompleted ? <CheckCircle className="w-5 h-5" /> : <Icon className="w-5 h-5" />}
                    </div>
                    <span
                      className={`
                        text-xs font-medium
                        ${isActive ? 'text-purple-600' : ''}
                        ${isCompleted ? 'text-green-600' : ''}
                        ${!isActive && !isCompleted ? 'text-gray-400' : ''}
                      `}
                    >
                      {s.label}
                    </span>
                  </div>
                  {index < 3 && (
                    <div
                      className={`
                        flex-1 h-1 mx-2 rounded-full transition-all
                        ${isCompleted ? 'bg-green-600' : 'bg-gray-200'}
                      `}
                    />
                  )}
                </React.Fragment>
              );
            })}
          </div>
        </div>

        {/* Content */}
        <div className="p-6">
          {/* STEP 1: Upload Images */}
          {step === 'upload' && (
            <UploadStep
              images={images}
              imagePreviews={imagePreviews}
              variantLabels={variantLabels}
              dragOver={dragOver}
              onFileSelect={handleFileSelect}
              onDrop={handleDrop}
              onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
              onDragLeave={() => setDragOver(false)}
              onRemoveImage={removeImage}
              onNext={startAnalysis}
              onCancel={onClose}
              uploadMode={uploadMode}
              setUploadMode={setUploadMode}
              autoUploadSettings={autoUploadSettings}
              setAutoUploadSettings={setAutoUploadSettings}
              showSettings={showSettings}
              setShowSettings={setShowSettings}
            />
          )}

          {/* STEP 2: Analyzing */}
          {step === 'analyzing' && (
            <AnalyzingStep
              images={images}
              analyzingIndex={analyzingIndex}
              analysisProgress={analysisProgress}
              analysisError={analysisError}
            />
          )}

          {/* STEP 3: Results */}
          {step === 'results' && (
            <ResultsStep
              analysisResults={analysisResults}
              similarityResults={similarityResults}
              enhancedSimilarityResults={enhancedSimilarityResults}
              comparativeAnalysis={comparativeAnalysis || undefined} // Fix type mismatch
              recommendation={recommendation}
              onBack={() => setStep('upload')}
              onNext={generateCollagePreview}
              uploadMode={uploadMode}
              setUploadMode={setUploadMode}
              onAutoFillData={handleAutoFillData}
              analysisData={analysisResults[0]?.analysis} // Pass the first analysis result
            />
          )}

          {/* STEP 4: Collage & Submit */}
          {step === 'collage' && (
            <CollageStep
              collagePreview={collagePreview}
              variantLabels={variantLabels}
              variantCount={images.length}
              formData={productFormData}
              onFormChange={setProductFormData}
              onBack={() => setStep('results')}
              onSubmit={handleSubmit}
              uploadMode={uploadMode}
              onDirectUpload={handleDirectUpload}
            />
          )}
        </div>
      </div>
    </div>
  );
};

// Step Components (separate for clarity)

interface UploadStepProps {
  images: File[];
  imagePreviews: string[];
  variantLabels: string[];
  dragOver: boolean;
  onFileSelect: (files: FileList | null) => void;
  onDrop: (e: React.DragEvent) => void;
  onDragOver: (e: React.DragEvent) => void;
  onDragLeave: () => void;
  onRemoveImage: (index: number) => void;
  onNext: () => void;
  onCancel: () => void;
  uploadMode: 'direct' | 'review';
  setUploadMode: (mode: 'direct' | 'review') => void;
  // New props for Settings
  autoUploadSettings: any;
  setAutoUploadSettings: (settings: any) => void;
  showSettings: boolean;
  setShowSettings: (show: boolean) => void;
}

const UploadStep: React.FC<UploadStepProps> = ({
  images,
  imagePreviews,
  variantLabels,
  dragOver,
  onFileSelect,
  onDrop,
  onDragOver,
  onDragLeave,
  onRemoveImage,
  onNext,
  onCancel,
  uploadMode,
  setUploadMode,
  autoUploadSettings,
  setAutoUploadSettings,
  showSettings,
  setShowSettings
}) => {
  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-semibold text-gray-900 mb-2">Upload Variant Images</h3>
        <p className="text-sm text-gray-600">
          Upload 1 or more images. AI will analyze the FIRST image for patterns, lace details, pleats, and more.
          All images will be included in the final collage.
        </p>
        <div className="mt-2 p-3 bg-white border border-gray-200 rounded-lg shadow-sm">
          <label className="block text-sm font-medium text-gray-700 mb-2">Pilih Mode Upload:</label>
          <div className="grid grid-cols-2 gap-3">
            <button
              onClick={() => setUploadMode('review')}
              className={`p-3 rounded-lg border-2 text-left transition-all ${uploadMode === 'review'
                ? 'border-blue-500 bg-blue-50 text-blue-900'
                : 'border-gray-200 hover:border-blue-300'
                }`}
            >
              <div className="flex items-center gap-2 font-medium mb-1">
                <CheckCircle className="w-4 h-4" />
                Review Dulu
              </div>
              <p className="text-xs opacity-75">Cek hasil analisa & edit sebelum upload.</p>
            </button>
            <button
              onClick={() => setUploadMode('direct')}
              className={`p-3 rounded-lg border-2 text-left transition-all ${uploadMode === 'direct'
                ? 'border-green-500 bg-green-50 text-green-900'
                : 'border-gray-200 hover:border-green-300'
                }`}
            >
              <div className="flex items-center gap-2 font-medium mb-1">
                <Sparkles className="w-4 h-4" />
                Auto Upload
              </div>
              <p className="text-xs opacity-75">Upload OTOMATIS jika Sales &gt; 4 & Mirip &gt; 80%.</p>
            </button>
          </div>
        </div>
      </div>

      {/* Drop Zone */}
      <div
        onDrop={onDrop}
        onDragOver={onDragOver}
        onDragLeave={onDragLeave}
        className={`
          border-2 border-dashed rounded-lg p-8 text-center transition-all
          ${dragOver ? 'border-purple-500 bg-purple-50' : 'border-gray-300 hover:border-gray-400'}
        `}
      >
        <input
          type="file"
          id="image-upload"
          multiple
          accept="image/*"
          onChange={(e) => onFileSelect(e.target.files)}
          className="hidden"
        />
        <label
          htmlFor="image-upload"
          className="cursor-pointer"
        >
          <Upload className="w-12 h-12 text-gray-400 mx-auto mb-4" />
          <p className="text-gray-700 font-medium mb-1">
            Click to upload or drag and drop
          </p>
          <p className="text-sm text-gray-500">
            PNG, JPG up to 5MB each (3-9 images)
          </p>
        </label>
      </div>

      {/* Auto Upload Settings Panel */}
      {showSettings && (
        <div className="mb-4 p-4 bg-white border border-purple-200 rounded-xl shadow-sm">
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-4">
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">📦 Stok Per Varian</label>
              <input
                type="number"
                value={autoUploadSettings.stock}
                onChange={(e) => setAutoUploadSettings({ ...autoUploadSettings, stock: parseInt(e.target.value) || 0 })}
                className="w-full text-sm border-gray-300 rounded-lg focus:ring-purple-500 focus:border-purple-500"
                min="0"
              />
              <p className="text-[10px] text-gray-400 mt-1">Stok default tiap varian</p>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">💰 Harga Modal</label>
              <input
                type="number"
                value={autoUploadSettings.costPrice}
                onChange={(e) => setAutoUploadSettings({ ...autoUploadSettings, costPrice: parseInt(e.target.value) || 0 })}
                className="w-full text-sm border-gray-300 rounded-lg focus:ring-purple-500 focus:border-purple-500"
                min="0"
                step="5000"
              />
              <p className="text-[10px] text-gray-400 mt-1">Harga beli / modal produk</p>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-700 mb-1">🏷️ Potongan Reseller</label>
              <input
                type="number"
                value={autoUploadSettings.resellerDiscount}
                onChange={(e) => setAutoUploadSettings({ ...autoUploadSettings, resellerDiscount: parseInt(e.target.value) || 0 })}
                className="w-full text-sm border-gray-300 rounded-lg focus:ring-purple-500 focus:border-purple-500"
                min="0"
                step="5000"
              />
              <p className="text-[10px] text-gray-400 mt-1">Harga reseller = Retail - ini</p>
            </div>
          </div>

          {/* Enable Logic Checkbox */}
          <div className="flex items-center gap-3 mb-4 p-2 bg-purple-50 rounded-lg">
            <label className="flex items-center gap-2 text-sm text-gray-700 cursor-pointer">
              <input
                type="checkbox"
                checked={autoUploadSettings.enableCustomLogic}
                onChange={(e) => setAutoUploadSettings({ ...autoUploadSettings, enableCustomLogic: e.target.checked })}
                className="rounded text-purple-600 focus:ring-purple-500"
              />
              <span className="font-medium">⚡ Aktifkan Logic Otomatis</span>
            </label>
            <span className="text-[10px] text-purple-600">Harga retail dihitung otomatis dari modal + markup</span>
          </div>

          {/* Pricing Rules Section */}
          <div className="p-3 bg-gradient-to-br from-gray-50 to-purple-50 rounded-lg border border-purple-100">
            <div className="flex items-center justify-between mb-3">
              <h4 className="text-xs font-bold text-gray-700 flex items-center gap-1">
                📊 Logic Harga Retail (Multiple Rules)
              </h4>
              <button
                onClick={() => {
                  const newId = Date.now().toString();
                  const lastRule = autoUploadSettings.pricingRules[autoUploadSettings.pricingRules.length - 1];
                  const newRule = {
                    id: newId,
                    minCost: lastRule ? lastRule.maxCost + 1 : 0,
                    maxCost: lastRule ? lastRule.maxCost + 100000 : 100000,
                    retailMarkup: lastRule ? lastRule.retailMarkup + 10000 : 30000
                  };
                  setAutoUploadSettings({
                    ...autoUploadSettings,
                    pricingRules: [...autoUploadSettings.pricingRules, newRule]
                  });
                }}
                className="text-xs bg-purple-600 text-white px-2 py-1 rounded-md hover:bg-purple-700 transition-colors flex items-center gap-1"
              >
                + Tambah Rule
              </button>
            </div>

            <div className="space-y-2">
              {autoUploadSettings.pricingRules.map((rule, index) => (
                <div key={rule.id} className="flex items-center gap-2 p-2 bg-white rounded-lg border border-gray-200 shadow-sm">
                  <span className="text-xs font-bold text-purple-600 w-6">#{index + 1}</span>
                  <span className="text-xs text-gray-500">Jika Modal</span>
                  <input
                    type="number"
                    value={rule.minCost}
                    onChange={(e) => {
                      const newRules = [...autoUploadSettings.pricingRules];
                      newRules[index] = { ...rule, minCost: parseInt(e.target.value) || 0 };
                      setAutoUploadSettings({ ...autoUploadSettings, pricingRules: newRules });
                    }}
                    className="w-24 text-sm border-gray-300 rounded px-2 py-1 focus:ring-purple-500 focus:border-purple-500"
                    min="0"
                    step="10000"
                  />
                  <span className="text-xs text-gray-500">s/d</span>
                  <input
                    type="number"
                    value={rule.maxCost}
                    onChange={(e) => {
                      const newRules = [...autoUploadSettings.pricingRules];
                      newRules[index] = { ...rule, maxCost: parseInt(e.target.value) || 0 };
                      setAutoUploadSettings({ ...autoUploadSettings, pricingRules: newRules });
                    }}
                    className="w-24 text-sm border-gray-300 rounded px-2 py-1 focus:ring-purple-500 focus:border-purple-500"
                    min="0"
                    step="10000"
                  />
                  <span className="text-xs text-gray-500">→ Markup:</span>
                  <input
                    type="number"
                    value={rule.retailMarkup}
                    onChange={(e) => {
                      const newRules = [...autoUploadSettings.pricingRules];
                      newRules[index] = { ...rule, retailMarkup: parseInt(e.target.value) || 0 };
                      setAutoUploadSettings({ ...autoUploadSettings, pricingRules: newRules });
                    }}
                    className="w-24 text-sm border-gray-300 rounded px-2 py-1 bg-green-50 focus:ring-green-500 focus:border-green-500 font-medium text-green-700"
                    min="0"
                    step="5000"
                  />
                  {autoUploadSettings.pricingRules.length > 1 && (
                    <button
                      onClick={() => {
                        const newRules = autoUploadSettings.pricingRules.filter((r: PricingRule) => r.id !== rule.id);
                        setAutoUploadSettings({ ...autoUploadSettings, pricingRules: newRules });
                      }}
                      className="text-red-500 hover:text-red-700 p-1 rounded hover:bg-red-50 transition-colors"
                      title="Hapus rule"
                    >
                      <X className="w-4 h-4" />
                    </button>
                  )}
                </div>
              ))}
            </div>

            {/* Preview Calculation */}
            <div className="mt-3 p-2 bg-blue-50 rounded-lg border border-blue-100">
              <p className="text-[10px] text-blue-700 font-medium mb-1">📋 Preview Perhitungan:</p>
              <p className="text-xs text-blue-800">
                Modal: <strong>Rp {autoUploadSettings.costPrice.toLocaleString('id-ID')}</strong> →
                Retail: <strong>Rp {(() => {
                  const cost = autoUploadSettings.costPrice;
                  const matchingRule = autoUploadSettings.pricingRules.find(
                    (r: PricingRule) => cost >= r.minCost && cost <= r.maxCost
                  );
                  const markup = matchingRule?.retailMarkup || autoUploadSettings.pricingRules[0]?.retailMarkup || 0;
                  return (cost + markup).toLocaleString('id-ID');
                })()}</strong> →
                Reseller: <strong>Rp {(() => {
                  const cost = autoUploadSettings.costPrice;
                  const matchingRule = autoUploadSettings.pricingRules.find(
                    (r: PricingRule) => cost >= r.minCost && cost <= r.maxCost
                  );
                  const markup = matchingRule?.retailMarkup || autoUploadSettings.pricingRules[0]?.retailMarkup || 0;
                  return (cost + markup - autoUploadSettings.resellerDiscount).toLocaleString('id-ID');
                })()}</strong>
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Image Previews */}
      {images.length > 0 && (
        <div>
          <div className="flex items-center justify-between mb-3">
            <p className="text-sm font-medium text-gray-700">
              {images.length} image{images.length !== 1 ? 's' : ''} selected
            </p>
            <p className="text-xs text-gray-500">
              {images.length < 1 && `Need ${1 - images.length} more`}
              {images.length >= 1 && images.length < 9 && `Can add ${9 - images.length} more`}
              {images.length === 9 && 'Maximum reached'}
            </p>
          </div>

          <div className="grid grid-cols-3 sm:grid-cols-4 md:grid-cols-5 gap-3">
            {imagePreviews.map((preview, index) => (
              <div key={index} className="relative group">
                <div className="aspect-square rounded-lg overflow-hidden border-2 border-gray-200">
                  <img
                    src={preview}
                    alt={`Variant ${variantLabels[index]}`}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="absolute top-1 left-1 px-2 py-1 bg-black/75 text-white text-xs font-bold rounded">
                  {variantLabels[index]}
                </div>
                <button
                  onClick={() => onRemoveImage(index)}
                  className="absolute top-1 right-1 p-1 bg-red-600 text-white rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Actions */}
      <div className="flex gap-3 justify-end items-center">
        <div className="absolute left-6 bottom-6">
          <button
            onClick={() => setShowSettings(!showSettings)}
            className="flex items-center gap-2 text-xs font-semibold text-purple-600 bg-purple-50 px-3 py-2 rounded-lg hover:bg-purple-100 transition-colors"
          >
            <Settings className="w-4 h-4" />
            {showSettings ? 'Hide Parameters' : 'Auto Upload Parameters'}
            {showSettings ? <ChevronDown className="w-3 h-3" /> : <ChevronUp className="w-3 h-3" />}
          </button>
        </div>
        <button
          onClick={onCancel}
          className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg font-medium hover:bg-gray-50 transition-all"
        >
          Cancel
        </button>
        <button
          onClick={onNext}
          disabled={images.length < 1}
          className={`
            px-6 py-2 rounded-lg font-medium transition-all flex items-center gap-2
            ${images.length >= 1
              ? 'bg-gradient-to-r from-purple-600 to-blue-600 text-white hover:from-purple-700 hover:to-blue-700 shadow-lg'
              : 'bg-gray-100 text-gray-400 cursor-not-allowed'
            }
          `}
        >
          <Sparkles className="w-4 h-4" />
          Analyze with AI
        </button>
      </div>
    </div>
  );
};

interface AnalyzingStepProps {
  images: File[];
  analyzingIndex: number;
  analysisProgress: number;
  analysisError: string | null;
}

const AnalyzingStep: React.FC<AnalyzingStepProps> = ({
  images,
  analyzingIndex,
  analysisProgress,
  analysisError
}) => {
  return (
    <div className="space-y-6">
      <div className="text-center">
        <div className="inline-flex p-4 bg-purple-100 rounded-full mb-4">
          <Loader2 className="w-12 h-12 text-purple-600 animate-spin" />
        </div>
        <h3 className="text-lg font-semibold text-gray-900 mb-2">
          Analyzing with Gemini AI...
        </h3>
        <p className="text-sm text-gray-600">
          Detecting model, patterns, lace, pleats, and embellishments
        </p>
      </div>

      {/* Progress Bar */}
      <div>
        <div className="flex justify-between text-sm text-gray-600 mb-2">
          <span>Progress</span>
          <span>{Math.round(analysisProgress)}%</span>
        </div>
        <div className="w-full h-2 bg-gray-200 rounded-full overflow-hidden">
          <div
            className="h-full bg-gradient-to-r from-purple-600 to-blue-600 transition-all duration-300"
            style={{ width: `${analysisProgress}%` }}
          />
        </div>
      </div>

      {/* Image Analysis Status - Optimized for single image analysis */}
      <div className="space-y-2">
        <div className="flex items-center gap-3 p-4 rounded-lg border border-purple-300 bg-purple-50">
          <div>
            <Loader2 className="w-5 h-5 text-purple-600 animate-spin" />
          </div>
          <span className="flex-1 text-sm font-medium text-gray-700">
            Analyzing: {images[0]?.name || 'First image'}
          </span>
          <span className="text-xs text-purple-600">
            ⚡ Fast mode: Analyzing only first image
          </span>
        </div>

        {images.length > 1 && (
          <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg">
            <p className="text-xs text-blue-700">
              ℹ️ {images.length} images uploaded. Only first image is analyzed for faster processing.
              All images will be included in the final collage.
            </p>
          </div>
        )}
      </div>

      {/* Error */}
      {analysisError && (
        <div className="flex items-start gap-3 p-4 bg-red-50 border border-red-200 rounded-lg">
          <AlertCircle className="w-5 h-5 text-red-600 mt-0.5 flex-shrink-0" />
          <div className="flex-1">
            <p className="text-sm font-medium text-red-900 mb-1">Analysis Error</p>
            <p className="text-sm text-red-800">{analysisError}</p>
          </div>
        </div>
      )}
    </div>
  );
};

interface ResultsStepProps {
  analysisResults: AnalysisResult[];
  similarityResults: SimilarityResult[];
  enhancedSimilarityResults?: EnhancedSimilarityResultUI[];
  comparativeAnalysis?: {
    topSimilarities: Array<{
      productName: string;
      similarityScore: number;
      keySimilarities: string[];
      recommendation: string;
      reasoning: string;
    }>;
    overallRecommendation: string;
    marketInsights: string[];
  };
  recommendation: 'auto' | 'manual' | 'not_recommended';
  onBack: () => void;
  onNext: () => void;
  uploadMode: 'direct' | 'review';
  setUploadMode: (mode: 'direct' | 'review') => void;
  onAutoFillData: (product: Product, analysis: GeminiClothingAnalysis) => Promise<void>;
  analysisData: GeminiClothingAnalysis;
}

const ResultsStep: React.FC<ResultsStepProps> = ({
  analysisResults,
  similarityResults,
  enhancedSimilarityResults = [],
  comparativeAnalysis,
  recommendation,
  onBack,
  onNext,
  uploadMode,
  setUploadMode,
  onAutoFillData,
  analysisData
}) => {
  // Auto Upload Logic
  const [autoCheckStatus, setAutoCheckStatus] = useState<'checking' | 'qualified' | 'failed' | null>(null);
  const autoUploadTriggered = useRef(false);

  useEffect(() => {
    if (uploadMode === 'direct') {
      if (autoUploadTriggered.current) return; // Prevent double trigger

      setAutoCheckStatus('checking');

      // Check criteria: Sales > 4 AND Similarity > 80% (top match)
      const qualifiedProduct = enhancedSimilarityResults.find(p =>
        (p.overallScore || 0) >= 80 && (p.salesLast3Months || 0) > 4
      );

      if (qualifiedProduct) {
        console.log('✅ Auto Upload Qualified:', qualifiedProduct.product.name);
        setAutoCheckStatus('qualified');
        autoUploadTriggered.current = true;

        // Auto fill data with AI generation
        if (qualifiedProduct) {
          onAutoFillData(qualifiedProduct.product, analysisData).then(() => {
            // Auto proceed after delay (give time to see the checkmark)
            setTimeout(() => {
              onNext();
            }, 1000);
          });
        }

        return; // Wait for async operations
      } else {
        console.log('❌ Auto Upload Failed: Criteria not met');
        setAutoCheckStatus('failed');

        // Switch to manual review after delay
        const timer = setTimeout(() => {
          setUploadMode('review');
          // Optional: we can keep the 'failed' status visible for a bit longer via local state logic if needed
        }, 2000);
        return () => clearTimeout(timer);
      }
    }
  }, [uploadMode, enhancedSimilarityResults, onNext, setUploadMode]);

  // Calculate totals
  const totalSales = similarityResults.reduce((sum, s) => sum + s.salesLast3Months, 0);
  const avgSimilarity = similarityResults.length > 0
    ? similarityResults.reduce((sum, s) => sum + (s.score.overall_similarity || 0), 0) / similarityResults.length
    : 0;

  return (
    <div className="space-y-6">
      {/* Auto Upload Status */}
      {uploadMode === 'direct' && (
        <div className={`p-4 rounded-lg border-2 mb-4 transition-all ${autoCheckStatus === 'qualified' ? 'bg-green-50 border-green-500 text-green-800' :
          autoCheckStatus === 'failed' ? 'bg-yellow-50 border-yellow-500 text-yellow-800' :
            'bg-blue-50 border-blue-200 text-blue-800'
          }`}>
          <div className="flex items-center gap-3">
            {autoCheckStatus === 'checking' && <Loader2 className="w-5 h-5 animate-spin" />}
            {autoCheckStatus === 'qualified' && <CheckCircle className="w-5 h-5" />}
            {autoCheckStatus === 'failed' && <AlertTriangle className="w-5 h-5" />}

            <div>
              <p className="font-bold">
                {autoCheckStatus === 'checking' && 'Mengecek syarat Auto Upload...'}
                {autoCheckStatus === 'qualified' && '✅ Syarat Terpenuhi!'}
                {autoCheckStatus === 'failed' && '⚠️ Syarat Tidak Terpenuhi'}
              </p>
              <p className="text-sm mt-1">
                {autoCheckStatus === 'checking' && 'Syarat: Sales > 4 pcs & Mirip > 80%'}
                {autoCheckStatus === 'qualified' && 'Lanjut ke proses upload otomatis...'}
                {autoCheckStatus === 'failed' && 'Sales atau tingkat kemiripan tidak mencukupi. Beralih ke Manual Review.'}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Success Message */}
      <div className="flex items-start gap-3 p-4 bg-green-50 border border-green-200 rounded-lg">
        <CheckCircle className="w-5 h-5 text-green-600 mt-0.5 flex-shrink-0" />
        <div className="flex-1">
          <p className="text-sm font-medium text-green-900 mb-1">Analysis Complete!</p>
          <p className="text-sm text-green-800">
            Successfully analyzed {analysisResults.length} images. Compared with {similarityResults.length} similar products.
          </p>
        </div>
      </div>

      {/* Analysis Summary */}
      <div>
        <h3 className="text-lg font-semibold text-gray-900 mb-3">Analysis Summary</h3>
        <div className="space-y-3">
          {analysisResults.map((result, index) => {
            const analysis = result.analysis;
            return (
              <div key={index} className="p-4 border border-gray-200 rounded-lg">
                <div className="flex items-start gap-3">
                  <div className="px-3 py-1 bg-purple-100 text-purple-700 text-xs font-bold rounded">
                    {String.fromCharCode(65 + index)}
                  </div>
                  <div className="flex-1">
                    <p className="text-sm font-medium text-gray-900 mb-2">
                      {result.fileName}
                    </p>
                    <div className="grid grid-cols-2 gap-2 text-xs">
                      <div>
                        <span className="text-gray-500">Type:</span>{' '}
                        <span className="font-medium">{analysis.clothing_type.main_type}</span>
                      </div>
                      <div>
                        <span className="text-gray-500">Pattern:</span>{' '}
                        <span className="font-medium">{analysis.pattern_type.pattern}</span>
                      </div>
                      <div>
                        <span className="text-gray-500">Lace:</span>{' '}
                        <span className="font-medium">{analysis.lace_details.has_lace ? 'Yes' : 'No'}</span>
                      </div>
                      <div>
                        <span className="text-gray-500">Hem Pleats:</span>{' '}
                        <span className="font-medium">{analysis.hem_pleats.has_pleats ? 'Yes' : 'No'}</span>
                      </div>
                    </div>
                  </div>
                  <div className="text-xs text-gray-500">
                    {(result.processingTime / 1000).toFixed(1)}s
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Enhanced Similarity Results */}
      {enhancedSimilarityResults.length > 0 && (
        <div>
          <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center gap-2">
            <TrendingUp className="w-5 h-5" />
            AI Similarity Analysis (vs Bestsellers &gt;4pcs)
          </h3>

          {/* Overall Recommendation */}
          {comparativeAnalysis?.overallRecommendation && (
            <div className="mb-4 p-4 bg-gradient-to-r from-blue-50 to-purple-50 border border-blue-200 rounded-lg">
              <div className="flex items-start gap-3">
                <div className="p-2 bg-blue-100 rounded-lg">
                  <Sparkles className="w-5 h-5 text-blue-600" />
                </div>
                <div className="flex-1">
                  <p className="text-sm font-semibold text-blue-900 mb-1">AI Market Analysis</p>
                  <p className="text-sm text-blue-800">{comparativeAnalysis.overallRecommendation}</p>
                </div>
              </div>
            </div>
          )}

          {/* Top Similar Products */}
          <div className="space-y-3">
            {enhancedSimilarityResults.slice(0, 3).map((result, index) => {
              // Determine badge color based on recommendation
              let badgeColor = 'bg-gray-100 text-gray-800';
              let badgeIcon = <Info className="w-4 h-4" />;

              if (result.recommendation === 'highly_recommended') {
                badgeColor = 'bg-green-100 text-green-800';
                badgeIcon = <ThumbsUp className="w-4 h-4" />;
              } else if (result.recommendation === 'recommended') {
                badgeColor = 'bg-blue-100 text-blue-800';
                badgeIcon = <ThumbsUp className="w-4 h-4" />;
              } else if (result.recommendation === 'consider') {
                badgeColor = 'bg-yellow-100 text-yellow-800';
                badgeIcon = <AlertTriangle className="w-4 h-4" />;
              } else {
                badgeColor = 'bg-red-100 text-red-800';
                badgeIcon = <ThumbsDown className="w-4 h-4" />;
              }

              return (
                <div key={result.productId} className="border border-gray-200 rounded-lg overflow-hidden">
                  {/* Header with score and badge */}
                  <div className="p-4 bg-gray-50 border-b border-gray-200">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className={`px-3 py-1 rounded-full text-xs font-bold ${badgeColor} flex items-center gap-1`}>
                          {badgeIcon}
                          {result.recommendationLabel}
                        </div>
                        <span className="text-sm font-medium text-gray-700">
                          {index + 1}. {result.productName}
                        </span>
                      </div>
                      <div className="text-right">
                        <div className="text-2xl font-bold text-gray-900">{result.overallScore}%</div>
                        <div className="text-xs text-gray-500">Similarity Score</div>
                      </div>
                    </div>
                  </div>

                  {/* Breakdown and Details */}
                  <div className="p-4">
                    {/* Score Breakdown */}
                    <div className="mb-3">
                      <p className="text-xs font-medium text-gray-500 mb-2">Score Breakdown:</p>
                      <div className="grid grid-cols-5 gap-2">
                        <div className="text-center">
                          <div className="text-sm font-bold text-gray-900">{result.breakdown.modelType}%</div>
                          <div className="text-xs text-gray-500">Model</div>
                        </div>
                        <div className="text-center">
                          <div className="text-sm font-bold text-gray-900">{result.breakdown.pattern}%</div>
                          <div className="text-xs text-gray-500">Pattern</div>
                        </div>
                        <div className="text-center">
                          <div className="text-sm font-bold text-gray-900">{result.breakdown.colors}%</div>
                          <div className="text-xs text-gray-500">Colors</div>
                        </div>
                        <div className="text-center">
                          <div className="text-sm font-bold text-gray-900">{result.breakdown.details}%</div>
                          <div className="text-xs text-gray-500">Details</div>
                        </div>
                        <div className="text-center">
                          <div className="text-sm font-bold text-gray-900">{result.breakdown.embellishments}%</div>
                          <div className="text-xs text-gray-500">Embellish</div>
                        </div>
                      </div>
                    </div>

                    {/* Sales and Reasoning */}
                    <div className="flex items-start justify-between">
                      <div className="flex-1">
                        <p className="text-xs font-medium text-gray-500 mb-1">AI Reasoning:</p>
                        <p className="text-sm text-gray-700">{result.aiReasoning}</p>
                      </div>
                      <div className="ml-4 text-right">
                        <div className="text-lg font-bold text-green-600">{result.salesLast3Months}</div>
                        <div className="text-xs text-gray-500">Sales (3 months)</div>
                      </div>
                    </div>

                    {/* Recommendation Reason */}
                    <div className="mt-3 p-3 bg-gray-50 rounded-lg">
                      <p className="text-xs font-medium text-gray-500 mb-1">Recommendation:</p>
                      <p className="text-sm text-gray-700">{result.recommendationReason}</p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          {/* Market Insights */}
          {comparativeAnalysis?.marketInsights && comparativeAnalysis.marketInsights.length > 0 && (
            <div className="mt-4 p-4 bg-gradient-to-r from-purple-50 to-pink-50 border border-purple-200 rounded-lg">
              <h4 className="text-sm font-semibold text-purple-900 mb-2 flex items-center gap-2">
                <Sparkles className="w-4 h-4" />
                Market Insights
              </h4>
              <ul className="space-y-1">
                {comparativeAnalysis.marketInsights.map((insight, index) => (
                  <li key={index} className="text-sm text-purple-800 flex items-start gap-2">
                    <span className="text-purple-500 mt-1">•</span>
                    {insight}
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Summary Stats */}
          <div className="mt-4 grid grid-cols-3 gap-4">
            <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg">
              <p className="text-xs text-blue-600 mb-1">Products Checked</p>
              <p className="text-2xl font-bold text-blue-900">{enhancedSimilarityResults.length}</p>
              <p className="text-xs text-gray-500 mt-1">sales &gt;4pcs</p>
            </div>
            <div className="p-3 bg-purple-50 border border-purple-200 rounded-lg">
              <p className="text-xs text-purple-600 mb-1">High Match (&gt;80%)</p>
              <p className="text-2xl font-bold text-purple-900">
                {enhancedSimilarityResults.filter(s => s.overallScore > 80).length}
              </p>
              <p className="text-xs text-gray-500 mt-1">strong similarity</p>
            </div>
            <div className="p-3 bg-green-50 border border-green-200 rounded-lg">
              <p className="text-xs text-green-600 mb-1">Total Sales (3mo)</p>
              <p className="text-2xl font-bold text-green-900">
                {enhancedSimilarityResults.reduce((sum, s) => sum + s.salesLast3Months, 0)} pcs
              </p>
              <p className="text-xs text-gray-500 mt-1">from similar items</p>
            </div>
          </div>
        </div>
      )}

      {/* Recommendation */}
      {recommendation === 'auto' && (
        <div className="p-4 bg-green-50 border border-green-200 rounded-lg">
          <div className="flex items-start gap-3">
            <CheckCircle className="w-5 h-5 text-green-600 mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-sm font-semibold text-green-900 mb-1">✅ RECOMMENDED FOR UPLOAD</p>
              <p className="text-xs text-green-800">
                Ditemukan {similarityResults.filter(s => s.score.overall_similarity > 80).length} produk dengan kemiripan motif + model &gt;80%.
                Produk-produk tersebut memiliki sales history yang bagus ({similarityResults.reduce((sum, s) => sum + s.salesLast3Months, 0)} pcs).
                Produk baru ini berpotensi laku dengan baik!
              </p>
            </div>
          </div>
        </div>
      )}

      {recommendation === 'manual' && (
        <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
          <div className="flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-yellow-600 mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-sm font-semibold text-yellow-900 mb-1">⚠️ MANUAL REVIEW RECOMMENDED</p>
              <p className="text-xs text-yellow-800">
                Ada produk dengan kemiripan 60-80%, tapi tidak cukup tinggi untuk auto recommendation.
                Review hasil comparison sebelum upload.
              </p>
            </div>
          </div>
        </div>
      )}

      {recommendation === 'not_recommended' && (
        <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
          <div className="flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-red-600 mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-sm font-semibold text-red-900 mb-1">❌ LOW SIMILARITY</p>
              <p className="text-xs text-red-800">
                Tidak ditemukan produk dengan kemiripan motif + model &gt;80%.
                Ini adalah tipe produk baru yang belum ada di inventory.
              </p>
            </div>
          </div>
        </div>
      )}

      {similarityResults.length === 0 && (
        <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
          <p className="text-sm text-blue-800">
            <strong>💡 Note:</strong> Tidak ada produk dengan sales &gt;4pcs dalam 3 bulan terakhir.
            Ini adalah produk baru yang belum bisa dibandingkan!
          </p>
        </div>
      )}



      {/* Actions */}
      <div className="flex gap-3 justify-end">
        <button
          onClick={onBack}
          className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg font-medium hover:bg-gray-50 transition-all"
        >
          Back
        </button>
        <button
          onClick={onNext}
          className="px-6 py-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-lg font-medium hover:from-purple-700 hover:to-blue-700 shadow-lg transition-all flex items-center gap-2"
        >
          <ImageIcon className="w-4 h-4" />
          Lanjut ke Collage
        </button>
      </div>
    </div>
  );
};

interface CollageStepProps {
  collagePreview: string | null;
  variantLabels: string[];
  variantCount: number;
  formData: any;
  onFormChange: (data: any) => void;
  onBack: () => void;
  onSubmit: () => void;
  uploadMode: 'direct' | 'review';
  onDirectUpload: () => void;
}

const CollageStep: React.FC<CollageStepProps> = ({
  collagePreview,
  variantLabels,
  variantCount,
  formData,
  onFormChange,
  onBack,
  onSubmit,
  uploadMode,
  onDirectUpload
}) => {
  const layout = collageService.getOptimalLayout(variantCount);
  const dimensions = collageService.getCollageDimensions(variantCount);

  // Auto Submit for Direct Upload Mode
  const autoSubmitTriggered = useRef(false);

  useEffect(() => {
    if (uploadMode === 'direct') {
      if (autoSubmitTriggered.current) return; // Prevent double submit
      autoSubmitTriggered.current = true;

      const timer = setTimeout(() => {
        onDirectUpload();
      }, 1000);
      return () => clearTimeout(timer);
    }
  }, [uploadMode, onDirectUpload]);

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-semibold text-gray-900 mb-2">Collage Preview</h3>
        <p className="text-sm text-gray-600">
          Review the collage and fill in product details to complete the upload.
        </p>
      </div>

      {/* Collage Preview */}
      {collagePreview && (
        <div className="border-2 border-gray-200 rounded-lg overflow-hidden">
          <img
            src={collagePreview}
            alt="Product Collage"
            className="w-full"
          />
          <div className="p-3 bg-gray-50 border-t border-gray-200">
            <div className="flex items-center justify-between text-xs text-gray-600">
              <span>Layout: {layout.rows}×{layout.cols} grid</span>
              <span>{dimensions.width}×{dimensions.height}px</span>
              <span>{variantCount} variants ({variantLabels.join(', ')})</span>
            </div>
          </div>
        </div>
      )}

      {/* Product Form */}
      <div className="space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Product Name *
          </label>
          <input
            type="text"
            value={formData.name}
            onChange={(e) => onFormChange({ ...formData, name: e.target.value })}
            placeholder={`Gamis Premium ${variantLabels.join('-')}`}
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Deskripsi Produk
          </label>
          <textarea
            value={formData.description}
            onChange={(e) => onFormChange({ ...formData, description: e.target.value })}
            placeholder={`${variantCount} varian: ${variantLabels.join(', ')}. Model dengan motif unik...`}
            rows={3}
            className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
          />
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Harga Beli/Modal *
            </label>
            <input
              type="number"
              value={formData.costPrice}
              onChange={(e) => {
                const newCost = e.target.value;
                const retail = parseInt(formData.retailPrice) || 0;
                const profit = calculateProfit(retail, parseInt(newCost) || 0);
                onFormChange({ ...formData, costPrice: newCost, profitMargin: profit });
              }}
              placeholder="100000"
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Harga Retail *
            </label>
            <input
              type="number"
              value={formData.retailPrice}
              onChange={(e) => {
                const newRetail = e.target.value;
                const cost = parseInt(formData.costPrice) || 0;
                const profit = calculateProfit(parseInt(newRetail) || 0, cost);
                onFormChange({ ...formData, retailPrice: newRetail, profitMargin: profit });
              }}
              placeholder="150000"
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Harga Reseller *
            </label>
            <input
              type="number"
              value={formData.resellerPrice}
              onChange={(e) => onFormChange({ ...formData, resellerPrice: e.target.value })}
              placeholder="135000"
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Profit Margin
            </label>
            <div className={`px-3 py-2 rounded-lg font-bold text-center ${formData.profitMargin > 30 ? 'bg-green-100 text-green-800' :
              formData.profitMargin > 15 ? 'bg-yellow-100 text-yellow-800' :
                'bg-red-100 text-red-800'
              }`}>
              {formData.profitMargin}%
            </div>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Category
            </label>
            <select
              value={formData.category}
              onChange={(e) => onFormChange({ ...formData, category: e.target.value })}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
            >
              <option value="Gamis">Gamis</option>
              <option value="Tunik">Tunik</option>
              <option value="Dress">Dress</option>
              <option value="Hijab">Hijab</option>
              <option value="Khimar">Khimar</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Total Stok (Semua Varian)
            </label>
            <div className={`px-3 py-2 rounded-lg font-bold text-center ${Object.values(formData.stockPerVariant).reduce((sum: number, stock: any) => sum + parseInt(String(stock) || '0'), 0) > 50
              ? 'bg-green-100 text-green-800'
              : Object.values(formData.stockPerVariant).reduce((sum: number, stock: any) => sum + parseInt(String(stock) || '0'), 0) > 0
                ? 'bg-yellow-100 text-yellow-800'
                : 'bg-red-100 text-red-800'
              }`}>
              {Object.values(formData.stockPerVariant).reduce((sum: number, stock: any) => sum + parseInt(String(stock) || '0'), 0)} pcs
            </div>
          </div>
        </div>

        {/* Stock per Variant */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Stok per Varian *
          </label>
          <div className="grid grid-cols-3 md:grid-cols-5 gap-3">
            {variantLabels.map((label) => (
              <div key={label} className="space-y-1">
                <div className="text-xs font-medium text-gray-600 bg-gray-100 rounded px-2 py-1 text-center">
                  Varian {label}
                </div>
                <input
                  type="number"
                  value={formData.stockPerVariant[label] || ''}
                  onChange={(e) => onFormChange({
                    ...formData,
                    stockPerVariant: {
                      ...formData.stockPerVariant,
                      [label]: e.target.value
                    }
                  })}
                  placeholder="0"
                  min="0"
                  className="w-full px-2 py-1 border border-gray-300 rounded focus:ring-2 focus:ring-purple-500 focus:border-transparent text-center"
                />
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Upload Mode Indicator */}
      {uploadMode && (
        <div className={`p-3 rounded-lg ${uploadMode === 'direct'
          ? 'bg-green-50 border border-green-200'
          : 'bg-blue-50 border border-blue-200'
          }`}>
          <div className="flex items-center gap-2">
            {uploadMode === 'direct' ? (
              <Sparkles className="w-5 h-5 text-green-600" />
            ) : (
              <CheckCircle className="w-5 h-5 text-blue-600" />
            )}
            <span className={`font-medium ${uploadMode === 'direct' ? 'text-green-900' : 'text-blue-900'
              }`}>
              Mode: {uploadMode === 'direct' ? 'Langsung Upload' : 'Review Upload'}
            </span>
          </div>
          <p className={`text-sm mt-1 ${uploadMode === 'direct' ? 'text-green-700' : 'text-blue-700'
            }`}>
            {uploadMode === 'direct'
              ? '✨ AI caption otomatis & upload langsung'
              : '✅ Review semua data sebelum upload'
            }
          </p>
        </div>
      )}

      {/* Actions */}
      <div className="flex gap-3 justify-end">
        {uploadMode === 'direct' ? (
          <button
            onClick={onDirectUpload}
            className="px-6 py-2 bg-gradient-to-r from-green-600 to-emerald-600 text-white rounded-lg font-medium hover:from-green-700 hover:to-emerald-700 shadow-lg transition-all flex items-center gap-2"
          >
            <Sparkles className="w-4 h-4" />
            Langsung Upload
          </button>
        ) : (
          <button
            onClick={onSubmit}
            className="px-6 py-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-lg font-medium hover:from-purple-700 hover:to-blue-700 shadow-lg transition-all flex items-center gap-2"
          >
            <Upload className="w-4 h-4" />
            Upload Produk
          </button>
        )}

        <button
          onClick={onBack}
          className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg font-medium hover:bg-gray-50 transition-all"
        >
          Back
        </button>
      </div>
    </div>
  );
};

export default AIAutoUploadModal;
